// Generated by https://quicktype.io

interface Member {
  id: number;
  name: string;
  role: string;
  status: string;
  image: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}

interface Achievement {
  id: number;
  member_id: string;
  achievement: string;
  image?: File;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}


interface Product {
  id: number;
  product: string;
  description: string;
  category: string;
  image?: File;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}
