// Generated by https://quicktype.io

interface Member {
  id: string;
  name: string;
  role: string;
  status: string;
  image?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}

interface Product {
  id: string;
  product: string;
  description: string;
  category: string;
  on_development: boolean;
  image?: File;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}

interface EventTypes {
  id: string;
  name: string;
  date: string;
  detail: string;
  organizer: string;
  image: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;

}

interface Pagination {
  page: number;
  size: number,
  totalData: number,
  totalPage: number
}

interface BaseResponse {
  message: string;
  pagination: Pagination;
}