// Generated by https://quicktype.io

interface Member {
  id: string;
  name: string;
  role: string;
  status: string;
  image?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}

interface Achievement {
  id: string;
  member_id: string;
  achievement: string;
  image?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}

interface Product {
  id: string;
  product: string;
  description: string;
  category: string;
  on_development: boolean;
  image?: File;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  deletedAt?: Date | string;
}
